<a href="https://colab.research.google.com/github/stacy-kendi/sklearn_supervised_models/blob/main/Scikit_Learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Classification

**Without Train Test Split**

In [26]:
churn_df = pd.read_csv('telecom_churn_clean.csv')

In [27]:
#Sample Test Data
X_test = ([
    [54,2.12],
    [33,20.1],
    [40.1,34]
])

In [28]:
#Building a K-Nearest Neighbout classification Model Using Majority Voting
from sklearn.neighbors import KNeighborsClassifier
X = churn_df[["total_day_charge", "total_eve_charge"]].values
Y = churn_df["churn"].values
print(X)
print(Y)
knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(X, Y)
testData_churn_prediction = knn.predict(X_test)
print(testData_churn_prediction)


[[45.07 16.78]
 [27.47 16.62]
 [41.38 10.3 ]
 ...
 [30.74 24.55]
 [36.35 13.57]
 [39.85 22.6 ]]
[0 0 0 ... 0 0 0]
[0 0 1]


**Train Test Split**

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=1, stratify=Y)

#model building
knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(X_train, Y_train)
prediction = knn.predict(X_test)
print(knn.score(X_test, Y_test)) #gives the accuracy

#Model Performance Evaluation
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(Y_test, prediction))
print(classification_report(Y_test, prediction))



0.87
[[844  11]
 [119  26]]
              precision    recall  f1-score   support

           0       0.88      0.99      0.93       855
           1       0.70      0.18      0.29       145

    accuracy                           0.87      1000
   macro avg       0.79      0.58      0.61      1000
weighted avg       0.85      0.87      0.84      1000



#Linear Regression

In [30]:
diabetes_df = pd.read_csv("diabetes_clean.csv")
#print(diabetes_df.head(5))

#Specifying the Features and Target
X = diabetes_df.drop("diabetes", axis=1).values
Y = diabetes_df["diabetes"].values
print(X.shape, Y.shape)

#Using Only a Single Feature
# X_bmi = X[:,5]
# X_bmi = X_bmi.reshape(-1, 1)
# print(X_bmi.shape, Y.shape)

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=1, stratify=Y)
regModel = LinearRegression()
regModel.fit(X_train,Y_train)
predict = regModel.predict(X_test)
#print(predict)
print(regModel.score(X_test, Y_test))


#Cross Validation
from sklearn.model_selection import cross_val_score, KFold
kf = KFold(n_splits=6, shuffle=True, random_state=42)
reg = LinearRegression()
cross_val = cross_val_score(reg, X, Y, cv=kf) #generates scores of each fold for linear regression the score is by default R-squared but it can be any score ie accuracy, mean etc
print(f"\n crossval: {cross_val}")
np.quantile(cross_val,[])

(768, 8) (768,)
0.23379511599846048

 crossval: [0.2400084  0.23561553 0.31257089 0.25591931 0.23838398 0.32004673]


array([], dtype=float64)

L# New section

# Logistic Regression

In [31]:
from sklearn.linear_model import LogisticRegression

#Import Dataset
diabetes_df = pd.read_csv("diabetes_clean.csv")

#Separate Target and Feature Values
X = diabetes_df.drop("diabetes", axis=1).values
Y = diabetes_df["diabetes"].values

#Splitting Data into Train and Test Datasets
X_train, X_test, Y_train, Y_Test = train_test_split(X, Y, test_size = 0.2, random_state=42, stratify=Y)

#Building the Logistic Regression Model
logModel = LogisticRegression()
logModel.fit(X_train, Y_train)
prediction = logModel.predict(X_test)
print(logModel.score(X_test, Y_test))
prediction_probability = logModel.predict_proba(X_test) #gives probability of each class ie [0,1] the final prediction is picked from the class with the highest probability
#print(prediction)
#print(prediction_probability)

#Performance Evaluation
from sklearn.metrics import classification_report, confusion_matrix
print(f"\n Confusion Matrix: {confusion_matrix(Y_test, prediction)}")
print(f"\n Classification Report: {classification_report(Y_test, prediction)}")


0.5584415584415584

 Confusion Matrix: [[70 30]
 [38 16]]

 Classification Report:               precision    recall  f1-score   support

           0       0.65      0.70      0.67       100
           1       0.35      0.30      0.32        54

    accuracy                           0.56       154
   macro avg       0.50      0.50      0.50       154
weighted avg       0.54      0.56      0.55       154



/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
