<a href="https://colab.research.google.com/github/stacy-kendi/sklearn_supervised_models/blob/main/Scikit_Learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Classification

**Without Train Test Split**

In [2]:
churn_df = pd.read_csv('telecom_churn_clean.csv')

In [28]:
#Sample Test Data
X_test = ([
    [54,2.12],
    [33,20.1],
    [40.1,34]
])

In [30]:
#Building a K-Nearest Neighbout classification Model Using Majority Voting
from sklearn.neighbors import KNeighborsClassifier
X = churn_df[["total_day_charge", "total_eve_charge"]].values
Y = churn_df["churn"].values
print(X)
print(Y)
knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(X, Y)
testData_churn_prediction = knn.predict(X_test)
print(testData_churn_prediction)

[[45.07 16.78]
 [27.47 16.62]
 [41.38 10.3 ]
 ...
 [30.74 24.55]
 [36.35 13.57]
 [39.85 22.6 ]]
[0 0 0 ... 0 0 0]
[0 0 1]


**Train Test Split**

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=1, stratify=Y)

#model building
knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(X_train, Y_train)
print(knn.score(X_test, Y_test)) #gives the accuracy



0.87


#Regression

In [34]:
diabetes_df = pd.read_csv("diabetes_clean.csv")
#print(diabetes_df.head(5))

#Specifying the Features and Target
X = diabetes_df.drop("diabetes", axis=1).values
Y = diabetes_df["diabetes"].values
print(X.shape, Y.shape)

#Using Only a Single Feature
# X_bmi = X[:,5]
# X_bmi = X_bmi.reshape(-1, 1)
# print(X_bmi.shape, Y.shape)

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=1, stratify=Y)
regModel = LinearRegression()
regModel.fit(X_train,Y_train)
predict = regModel.predict(X_test)
#print(predict)
print(regModel.score(X_test, Y_test))

#Cross Validation
from sklearn.model_selection import cross_val_score, KFold
kf = KFold(n_splits=6, shuffle=True, random_state=42)
reg = LinearRegression()
cross_val = cross_val_score(reg, X, Y, cv=kf) #generates scores of each fold for linear regression the score is by default R-squared but it can be any score ie accuracy, mean etc
print(f"\n crossval: {cross_val}")
np.quantile(cross_val,[])

(768, 8) (768,)
0.23379511599846048

 crossval: [0.2400084  0.23561553 0.31257089 0.25591931 0.23838398 0.32004673]
